### ISSUE TITLE
Why accounts.uuid not unique or without index?

### ISSUE THREAD

**Issue by 4n70w4** [spatie/larabank-aggregates#15]
Also why `accounts.user_id` without a foreign key?

Does this require event sourcing architecture or is it simply not done because of laziness?

Please explain.

**Comment by jpickwell** [comment]
I wouldn't say it's because of laziness, but rather they're not strictly needed for this demo app.

In a real world app, I would do this:
```php
// Laravel 7
$table->id(); // $table->bigIncrements("id");

// uuid is better than string because it will take advantage of the native UUID type if it exists
// unique is both an index and a constraint
$table->uuid("uuid")->unique();
```

Or, my personal preference:
```php
// just use a UUID as the primary key, and forego an incrementing integer ID
// primary keys are required to be unique, and are also indexed
$table->uuid("id")->primary();
```

The latter one should probably only be used when a native UUID type is available.

As for foreign keys, they can be nice, but are not strictly necessary even in real world apps, IMO.

These omissions in the demo are not because of some event sourcing requirements, but simply because this is a quick demo to give users a bit of guidance in how to integrate the event sourcing package into their application(s). This demo isn't even using the latest version of the event sourcing library.

**Comment by keizah7** [comment]
After replaying event `accounts` has duplicate accounts. How to solve this?
